spring.application.name=ApiGateway

#Port Setup
server.port=8084

#Eureka Setup
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

#API Gateway Setup
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true
spring.cloud.compatibility-verifier.enabled=false
spring.cloud.gateway.loadbalancer.use-sticky-session=true

#Microservice Path Config
spring.cloud.gateway.routes[0].id=product-ms
spring.cloud.gateway.routes[0].uri=lb://product-ms
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/products/**, /api/inventories/**

spring.cloud.gateway.routes[1].id=customer-ms
spring.cloud.gateway.routes[1].uri=lb://customer-ms
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/customers/**

spring.cloud.gateway.routes[2].id=order-ms
spring.cloud.gateway.routes[2].uri=lb://order-ms
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/orders/**


