spring.application.name=ApiGateway

#Port Setup
server.port=8085

#Eureka Setup
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

#API Gateway Setup
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true
spring.cloud.compatibility-verifier.enabled=false
spring.cloud.gateway.loadbalancer.use-sticky-session=true
spring.cloud.gateway.httpclient.ssl.enabled=false

#Microservice Path Config
spring.cloud.gateway.routes[0].id=product-ms
spring.cloud.gateway.routes[0].uri=lb://product-ms
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/products/**, /api/inventories/**

spring.cloud.gateway.routes[1].id=customer-ms
spring.cloud.gateway.routes[1].uri=lb://customer-ms
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/customers/**

spring.cloud.gateway.routes[2].id=order-ms
spring.cloud.gateway.routes[2].uri=lb://order-ms
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/orders/**

spring.main.allow-bean-definition-overriding=true
okta.oauth2.issuer=https://dev-83939578.okta.com/oauth2/default
okta.oauth2.client-id=your-client-id
okta.oauth2.client-secret=your-client-secret
okta.oauth2.redirect-uri-template=http://localhost:8085/login/oauth2/code/okta
okta.oauth2.scope=openid profile email


